config/routes.rb
Rails.application.routes.draw do
  resources :contests, except: [:detroy]
    delete 'contests/:id' => 'contests#destroy', as: :contest_destroy
  namespace :api do
    resources :photos
  end

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup'  => 'users#new'
  resources :users

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'contest/:id/photo/:photo_id' => 'contests#enter_contest', as: :enter_contest

  get 'contests/:id/start' => 'contests#start', as: :start_contest
  get 'contests/:id/vote' => 'contests#vote'
  put 'contests/:id/vote' => 'contests#vote', as: :vote
  get 'contests/:id/rankings' => 'contests#ranking', as: :ranking

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :photos, dependent: :nullify
  belongs_to :user

  validates :name, presence: true
  validates :criteria, presence: true
  
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :logged_in_user, except: [:index, :show, :start, :vote] #don't have to login to do this
  before_action :admin_user,     only: [:destroy] #only admin can do this
  before_action :contest_owner, only: [:edit, :update]
  before_action :has_2_photos, only: [:start]

  def index
    @contests = Contest.all
  end

  def new
    @contest = Contest.new
  end

  def show
    @contest = Contest.find(params[:id])
    @user = current_user
  end

  def create
    @contest = Contest.new(contest_params)
    @contest.user = current_user
    @contest.save
    if @contest.save
      redirect_to contests_path
    else
      render :new
    end
  end

  def enter_contest
    @contest = Contest.find(params[:id])
    @photo = Photo.find(params[:photo_id])
    @photo.contest = @contest
    if @photo.save
      redirect_to contest_path(@contest)
    end
  end

  def start
    @contest = Contest.find(params[:id])

    @random_photos = @contest.photos.limit(20).order("vote_counter ASC")
    try_counter = 0
    @photo1 = @random_photos[try_counter]
    @photo2 = match_photo2(@photo1)

    # in case no candidates
    if @photo2.nil?
      try_counter += 1
      @photo1 = @random_photos[try_counter]
      @photo2 = match_photo2(@photo1)
      if (try_counter == @random_photos.size - 1) && @photo2.nil?
        flash[:danger] = "No available photo matches."
        redirect_to @contest
      end
    end
  end

  def match_photo2 photo1
    # search +/- 100
    @lo_range = photo1.score - 100
    @hi_range = photo1.score + 100
    @photo2_candidates = @contest.photos.where(score: @lo_range..@hi_range).limit(10).order("RANDOM()")
    return @photo2 = @photo2_candidates.where.not(id: @photo1.id).limit(1).order("RANDOM()")[0] unless @photo2.nil?

    # search +/- 200
    @lo_range = photo1.score - 200
    @hi_range = photo1.score + 200
    @photo2_candidates = @contest.photos.where(score: @lo_range..@hi_range).limit(10).order("RANDOM()")
    return @photo2 = @photo2_candidates.where.not(id: @photo1.id).limit(1).order("RANDOM()")[0] unless @photo2.nil?

    # search +/- 300
    @lo_range = photo1.score - 300
    @hi_range = photo1.score + 300
    @photo2_candidates = @contest.photos.where(score: @lo_range..@hi_range).limit(10).order("RANDOM()")
    return @photo2 = @photo2_candidates.where.not(id: @photo1.id).limit(1).order("RANDOM()")[0] unless @photo2.nil?

    # search +/- 400
    @lo_range = photo1.score - 400
    @hi_range = photo1.score + 400
    @photo2_candidates = @contest.photos.where(score: @lo_range..@hi_range).limit(10).order("RANDOM()")
    return @photo2 = @photo2_candidates.where.not(id: @photo1.id).limit(1).order("RANDOM()")[0]
  end

  def vote
    @contest = Contest.find(params[:id])
    @photo1 = Photo.find(params[:up_photo_id])
    @photo2 = Photo.find(params[:down_photo_id])
    photo1_current_score = @photo1.score
    photo2_current_score = @photo2.score
    @photo1.upvote(photo2_current_score)
    @photo2.downvote(photo1_current_score)

    redirect_to start_contest_path
  end


  def ranking
    @contest = Contest.find(params[:id])
    @photos = @contest.photos.limit(10).order(score: :desc)
  end

  def contest_owner
    @contest = Contest.find(params[:id])

    if @contest.user != current_user
      flash[:danger] = "You are not the owner of this contest."
      redirect_to(root_url) unless @contest.user = current_user.admin
    end
  end

  def has_2_photos
    @contest = Contest.find(params[:id])
    unless @contest.photos.size >= 2
      flash[:danger] = "Not enough photos in current contest."
      redirect_to contest_path
    end

  end

  private

  def contest_params
    params.require(:contest).permit(:name, :criteria)
  end


end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/edit.html.erb
<h1>Contests#edit</h1>
<p>Find me in app/views/contests/edit.html.erb</p>

app/views/contests/index.html.erb
<h1>Contests</h1>
<div class="bg3"></div>
<% if logged_in? %>
    <%= link_to("Create Contest", new_contest_path) %>
<% end %>
<ul>
<% @contests.each do |contest|%>
	<li>
		<h3><%= link_to "#{contest.name}", contest_path(contest) %></h3>
		<%= link_to "Top 10", ranking_path(contest) %>
		<% if @current_user.admin %>
			 | <%= link_to "Destroy Contest", contest,  method: :delete %>
		<% end %>
	</li>
	
<% end %>
</ul>

app/views/contests/new.html.erb
<% provide(:title, 'New Contest') %>
<h1>New Contest</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @contest do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :criteria %>
      <%= f.text_area :criteria, class: 'form-control' %>

      <%= f.submit "Create contest", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/contests/ranking.html.erb
<h1><%= @contest.name %></h1>


<section id="list_ranked_photo">

	<% @photos.each do |photo| %>

		<div class="ranks_photos">
			
			<%= image_tag photo.image, class: "ranked_photo" %>
		</div>

	<% end %>

</section>

app/views/contests/show.html.erb
<h1>Contest name: <%= @contest.name %></h1>
<h2>Contest criteria: <%= @contest.criteria %></h2>
<div class="bg4"></div>
<div class="bg-overlay"></div>
<%= "Number of photos in this contest: #{@contest.photos.size}" %>
<br>
<br>    
<br>
<br>
<br>

<%= link_to("Vote in this contest", start_contest_path) %>
<br>
<br>
<br>
<br>
<br>

<% if logged_in? %>
	<h3>Your photos in contest: </h3>
	<br>
	<div id="user_contest_index">
	<% if @contest.photos.where(user_id: current_user.id).empty? %>
	  <p>No photos in this contest yet</p>
	<% end %>

	<% @contest.photos.where(user_id: current_user.id).each do |photo| %>
		<div class="user_contest_photo">
	    	<%= image_tag photo.image, class: "contest_entry" %>
	    </div>
	<% end %>
	</div>
	<br>
	<h3>Your Photos</h3>
	<br>
	<div id="user_index">
		<% if @user.photos.empty? %>
		  <p>You ain't gots no photos</p>
		<% end %>

		<% @user.photos.each do |photo| %>
		    <div class="user_photo">
		    	<%= link_to (image_tag photo.image, class: "user_contest_entry"), enter_contest_path(id: @contest.id, photo_id: photo.id)%>
		    </div>
		<% end %>
	</div>
<% end %>

app/views/contests/start.html.erb
<% if @contest.photos.size < 2 %>
    <p>not enough photos in this contest</p>
<% else %>
    <%= link_to image_tag(@photo1.image.url), vote_path(id: @contest.id, up_photo_id: @photo1.id, down_photo_id: @photo2.id) %>
    <%= link_to image_tag(@photo2.image.url), vote_path(id: @contest.id, up_photo_id: @photo2.id, down_photo_id: @photo1.id) %>
    <% if logged_in? && current_user.admin == true %>
        <br>
        <%= @photo1.score %>
        <%= @photo2.score %>
    <% end %>
<% end %>